# Deployment for service catalog api server. Two binaries are run in
# this deployment: service catalog apiserver and etcd. etc is run as a
# persistent volume. 
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: apiserver
  namespace: service-catalog
  labels:
    app: service-catalog-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-catalog-apiserver
  template:
    metadata:
      labels:
        app: service-catalog-apiserver
    spec:
      serviceAccountName: "apiserver"
      containers:
      - name: apiserver
        image: gcr.io/seans-sandbox/apiserver:canary
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        args:        
        - --admission-control
        - "KubernetesNamespaceLifecycle"
        - --secure-port
        - "8443"
        - --storage-type
        - etcd
        - --etcd-servers
        - http://etcd-svc:2379
        - -v
        - "6"
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: apiserver-cert
          mountPath: /var/run/kubernetes-service-catalog
          readOnly: true
        readinessProbe:
          httpGet:
            port: 8443
            path: /healthz
            scheme: HTTPS
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 8443
            path: /healthz
            scheme: HTTPS
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
      volumes:
      - name: apiserver-cert
        secret:
          secretName: apiserver-cert
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key

